# Generated by Django 3.0.8 on 2020-09-08 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devmo', '0003_auto_20200831_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categ', models.CharField(choices=[('Electronics', 'Electronics'), ('Beauty', 'Beauty'), ('Food', 'Food'), ('Sport', 'Sport'), ('Other', 'Other')], max_length=100, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-id']},
        ),
        migrations.CreateModel(
            name='User_followers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers', models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='devmo.Categories'),
        ),
    ]
