# Generated by Django 3.0.8 on 2020-09-08 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devmo', '0004_auto_20200908_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='categ',
            field=models.CharField(choices=[('web development', 'web development'), ('java script', 'java script'), ('UI design', 'UI design'), ('UX design', 'UX design'), ('python', 'python'), ('django', 'django')], max_length=100, null=True),
        ),
    ]
