# Generated by Django 3.0.8 on 2020-09-08 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devmo', '0005_auto_20200908_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_followers',
            name='user_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
