# Generated by Django 3.0.8 on 2020-09-13 22:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devmo', '0007_auto_20200913_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
